config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get '/main' => 'main#index'

  get '/:region_slug' => 'main#index', region_slug: /spb|siberia|south|volga/

  get '/rubrics/:rubric_slug' => 'main#rubric', rubric_slug: /[a-z0-9_]+/, as: :rubric
  get '/rubrics/:rubric_slug/:subrubric_slug' => 'main#subrubric', rubric_slug: /[a-z0-9_]+/, subrubric_slug: /[a-z0-9_]+/, as: :subrubric

  # parts
  get '/parts/:part_slug' => 'main#part', part_slug: /[a-z0-9_]+/, as: :part
  get '/parts/:part_slug/:subpart_slug' => 'main#subpart', part_slug: /video/, subpart_slug: /[a-z0-9_]+/, as: :subpart

  # newspaper
  get '/newspaper/:year/:month/calendar'   => 'newspaper#calendar', year: /\d{4}/, month: /\d{2}/
  get '/newspaper/:year/:month/:day'       => 'newspaper#by_date',  year: /\d{4}/, month: /\d{2}/, day: /\d{2}/, as: :newspaper
  get '/newspaper/last'                    => 'newspaper#by_date', as: :newspaper_last

  # vedomosti&
  get '/partner'                         => 'partner#index'
  get '/partner/:year/:month/:day'       => 'partner#by_date',  year: /\d{4}/, month: /\d{2}/, day: /\d{2}/
  get '/partner/last'                    => 'partner#by_date'
  get '/partner/*url'                    => 'partner#show'

  # newspaper flash.xml
  get '/newspaper/:year/:month/:day/flash' => 'newspaper#flash', year: /\d{4}/, month: /\d{2}/, day: /\d{2}/, as: :newspaper_flash
  get '/newspaper/last/flash'              => 'newspaper#flash', as: :newspaper_last_flash
  get '/newspaper',                        to: redirect('/newspaper/last')

  # story
  get '/story/:slug' => 'stories#show', slug: /[a-z0-9_]+/, as: :stories
  get '/story/:slug/news' => 'stories#news', slug: /[a-z0-9_]+/

  # newsline
  get '/newsline'              => 'newsline#index', top: true
  get '/newsline(/top)'        => 'newsline#index', top: true
  get '/newsline/:rubric_slug' => 'newsline#index', rubric_slug: /[a-z0-9_]+/, as: :rubric_news

  get '/newsline/news/*oldurl' => 'document#oldnews' # для новостей со старыми урлами
  get '/fast_news'             => redirect('/newsline')

  # search
  get '/search' => 'search#index'

  # sign up
  get  '/sign_up' => 'register#sign_up_form'
  post '/sign_up_with_password' => 'register#sign_up_with_password'

  # password reset
  get  '/password_reset'                       => 'register#email_form',  as: :password_reset_email_form
  post '/password_reset'                       => 'register#check_email', as: :password_reset_email_send

  get  '/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/, as: :password_form
  post '/password_reset/:password_reset_token' => 'register#password_update', password_reset_token: /[a-z0-9_]+/, as: :password_send

  get  '/auth/:provider/callback' => 'register#oauth_callback', provider: /[a-z0-9_]+/
  post '/sign_up_with_oauth'      => 'register#sign_up_with_oauth'

  # sign in / out
  get  '/sign_in'  => 'session#sign_in_form', as: :sign_in
  get  '/sign_out' => 'session#sign_out',     as: :sign_out

  # sign in with password
  post '/sign_in_with_password' => 'session#sign_in_with_password'

  get '/blocked_user'      => 'session#blocked_user'
  get '/too_many_sessions' => 'session#too_many_sessions', as: :sessions_limit

  # sign in with oauth
  post '/sign_in_with_oauth'    => 'session#sign_in_with_oauth'
  get  '/auth/failure' => 'register#oauth_failure'

  get '/includes/session/yes'               => 'includes#get_session'
  get '/includes/popular24'                 => 'includes#popular24', as: :popular24
  get '/includes/story/:slug'               => 'includes#story', slug: /[a-z0-9_]+/
  get '/includes/redline'                   => 'includes#redline'
  get '/includes/companies/:slug/materials' => 'includes#materials_of_company'
  get '/includes/people/:slug/materials'    => 'includes#materials_of_person'

  # user registration confirm
  get  '/confirm' => 'register#confirm'

  # user profile include
  get '/includes/long_cache/user_profile(/:access_token)'          => 'includes#user_profile', owl_state: 'guest',               access_token: /[a-f0-9]+/
  get '/includes/long_cache/user_profile/:owl_state/:access_token' => 'includes#user_profile', owl_state: /guest|registered|authenticated/, access_token: /[a-f0-9]+/

  get '/includes/metynnis/*url' => 'includes#metynnis'

  get '/owl/body/:owl_status/:owl_reason/:owl_state/*url(.:format)' => 'document#owl_show', format: /json|html|xml/

  get '/includes/owl_smart/:owl_status/:owl_reason/:owl_state/newspaper/:year/:month/:day/issue' => 'newspaper#owl_newspaper_issue', year: /\d{4}/, month: /\d{2}/, day: /\d{2}/

  #online
  get 'online/template' => 'online#index'

  # libraries
  get '/library' => 'libraries#index', as: :libraries
  get '/library/:slug' => 'libraries#show', slug: /[a-z0-9_]+/, as: :library

  # sessions
  get '/session'               => 'session#create'
  get '/user/profile'          => 'users#show', as: :users_show
  post '/user/profile'         => 'users#update', as: :users_update
  post '/profile/accept_promo' => 'users#accept_promo'

  # info
  namespace :info, defaults: { controller: 'info' } do
    get  '/',         action: 'index'
    get  '/feedback', action: 'feedback'
    post '/feedback', action: 'send_feedback'
    get  '/contacts', action: 'contacts'
    get  '/:slug',    action: 'show', slug: /[a-z0-9_-]+/
  end

  # multimedia
  get '/multimedia' => 'main#multimedia'

  # podcasts
  get '/podcast'                    => redirect('/podcasts/last')
  get '/podcasts'                   => redirect('/podcasts/last')
  get '/podcasts/last'              => 'podcasts#last'
  get '/podcasts/:year/:month/:day' => 'podcasts#by_date'

  get '/tests/*url/q:step'             => 'tests#show'
  get '/tests/*url/r:result_id'        => 'tests#result'
  get '/tests/*url/s:index'            => 'tests#share'
  get '/tests/*url'                    => 'tests#show'
  get '/:rubric/test/*url/q:step'      => 'tests#show'
  get '/:rubric/test/*url/r:result_id' => 'tests#result'
  get '/:rubric/test/*url/s:index'     => 'tests#share'
  get '/:rubric/test/*url'             => 'tests#show'


  # broadcastings
  get '/:rubric/online/*url/check_new_posts/(:start_date)' => 'broadcastings#check_new_posts'
  get '/:rubric/online/*url/p:page' =>                        'broadcastings#show', page: /[1-9][0-9]*/
  get '/:rubric/online/*url' =>                               'broadcastings#show', page: 1

  # companies
  namespace :companies, defaults: { controller: 'companies' } do
    get '/'                                      => redirect('companies/index')
    get '/search',                               action: 'search'
    get '/:filter/',                             action: 'main', filter: /index|industries/
    get '/:filter/:slug',                        action: 'by_filter', filter: /index|industries/
    get '/:filter/:slug/groups/:group',          action: 'by_group', filter: /index|industries/
    get '/:slug',                                action: 'show', slug: /[a-z0-9_\-]+/, tab: 'about'
    get '/:slug/press_releases',                 action: 'press_releases', slug: /[a-z0-9_\-]+/
    get '/:slug/press_releases/:year',           action: 'press_releases_by_year', slug: /[a-z0-9_\-]+/, year: /\d{4}/

    get '/:slug/company_messages',               action: 'company_messages', slug: /[a-z0-9_\-]+/
    get '/:slug/company_messages/:year(/:page)', action: 'company_messages', slug: /[a-z0-9_\-]+/, year: /\d{4}/, page: /\d+/

    get '/:slug/all_press_releases',             action: 'all_press_releases', slug: /[a-z0-9_\-]+/
    get '/:slug/:tab',                           action: 'show', slug: /[a-z0-9_\-]+/, tab: /about|kso|policy/
  end
  get '/press_releases/*suburl'                  => 'companies#press_release'
  get '/company_messages/*suburl'                => 'companies#company_message'

  # people
  namespace :people, defaults: { controller: 'people' } do
    get '/'                               => redirect('people/index')
    get '/:filter',                       action: 'main', filter: /index/
    get '/:filter/:slug',                 action: 'by_filter', constraints: ->(req) { CGI::unescape(req.params[:slug]) =~ /[А-ЯЁA-Z]/ }, filter: /index/
    get '/:filter/:slug/groups/:group',   action: 'by_group',  constraints: ->(req) { CGI::unescape(req.params[:slug]) =~ /[А-ЯЁA-Z]/ && CGI::unescape(req.params[:group]) =~ /[А-ЯЁA-Z][а-яёa-z]+\s—\s[А-ЯЁA-Z][а-яёa-z]+/ }, filter: /index/
    get '/:filter/search',                action: 'search', filter: /index/
    get '/*url',                          action: 'show'
  end
  
  # mobile version
  constraints(SubdomainConstraints::M) do
    scope module: :m do
      get '/user/profile'  => 'users#show',   as: :m_users_show
      post '/user/profile' => 'users#update', as: :m_users_update
      get '/newsline/top/*url' => 'document#show', top: true
      get '/newsline/*url'     => 'document#show'
      get '/*url'              => 'document#show'
    end
  end

  namespace :advert, defaults: { controller: 'advert' } do
    get '/main', action: 'main'
    get '/noteads', action: 'noteads'
    get '/teads', action: 'teads'
    get '/mobile_main', action: 'mobile_main'
  end

  # subscription
  namespace :subscription, defaults: { controller: 'subscription' } do
    get '/',      action: 'engineering_works'
    get '/step1', action: 'engineering_works'
    get '/step2', action: 'engineering_works'
    get '/step3', action: 'engineering_works'

    get '/corporate',        action: 'corporate'
    get '/gift',             action: 'gift'
    get '/representational', action: 'representational'

    get '/prices', action: 'prices'

    post '/payment/card',    action: 'payment_card'
    post '/payment/yandex',  action: 'payment_yandex'

    get '/card_order_check/:uuid', action: 'card_order_check', uuid: /[a-f0-9\-]+/

    post '/card_callback',        action: 'card_callback'

app/controllers/api/v1/session_controller.rb
module Api
  module V1
    class SessionController < ApplicationController
      skip_before_filter :authorize_session!, only: :create
      
      def create
        set_session
        head :ok
      end
      
      def access_rights
        response = client.get(
          request.ip,
          "/shark/sessions/#{access_token}"
        )
        
        if response.success?
          render json: response.body
        else
          head :unauthorized
        end
      end
      
      def sign_in_with_password
        response = client.post(
          request.ip,
          '/shark/sign_in_with_password',
          email:        params[:email],
          password:     params[:password],
          access_token: access_token
        )
        
        if response.success?
          render json: response.body
        else
          head :unprocessable_entity
        end
      end
      
      def sign_in_with_oauth
        use_case = SignInWithOauthToken.new(
          request.ip,
          access_token,
          params[:provider],
          params[:oauth_token],
          params[:oauth_token_secret]
        )
        
        if use_case.call
          render json: use_case.user
        else
          render json: use_case.user, status: :accepted
        end
      end
      
      def sign_out
        client.delete(
          request.ip,
          '/shark/sign_out',
          access_token: access_token
        )
        head :ok
      end
      
    private
      def set_session
        data = client.post(
          request.ip,
          '/shark/sessions',
          session: { ip: request.ip },
          mobile: true
        ).body
        
        response.headers['X-Access-Token'] = data[:access_token]
      end
      
      def client
        AquariumClient.new
      end
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    if !Rails.env.production? || token_absent? || token_invalid?
      set_session
      ::NewRelic::Agent.increment_metric('Custom/Sessions/create')
    end

    redirect_to params.fetch(:url, root_path)
  end

  def sign_in_form
    set_return_to_cookie
    @sign_in_form = SignInForm.new
  end

  def sign_in_with_password
    @sign_in_form = SignInForm.new(
      access_token: access_token,
      ip: request.ip,
      **params.fetch(:sign_in_form, {}).symbolize_keys
    )

    use_case = SignInWithPassword.new(@sign_in_form)
    use_case.call

    if use_case.new_token.present?
      response.headers['Set-Cookie'] = token_cookie_header(use_case.new_token)
    end

    if use_case.success?
      respond_to do |format|
        format.html   { delete_cookie_and_redirect }
        format.mobile { delete_cookie_and_redirect }
        format.json   { render json: use_case.user_data }
      end
    elsif use_case.blocked?
      redirect_to blocked_user_url
    elsif use_case.too_many_sessions?
      redirect_to sessions_limit_url
    else
      respond_to do |format|
        format.html   { render 'session/sign_in_form' }
        format.mobile { render 'session/sign_in_form' }
        format.json   { head :unprocessable_entity }
      end
    end
  end

  def sign_out
    client.delete(
      request.ip,
      '/shark/sign_out',
      access_token: access_token
    )
    redirect_to request.referer || root_url
  end

private
  def set_session
    aquarium_response = client.post(
      request.ip,
      '/shark/sessions',
      session: { ip: request.ip }
    )

    if aquarium_response.success?
      response.headers['Set-Cookie'] = token_cookie_header(aquarium_response.body[:access_token])
    end
  end

  def client
    AquariumClient.new
  end

  def token_absent?
    !cookies.key?(:access_token) || cookies[:access_token].empty?
  end

  def token_invalid?
    return true if access_token.empty?
    client.get(request.ip, "/shark/users/#{access_token}")
    false
  rescue AquariumClient::Unauthorized
    return true
  end
end

app/views/session/blocked_user.html.slim
.b-document.b-document_user-block
  h1 К сожалению, Ваш аккаунт заблокирован
  p
    |Вы были заблокированы, так как не активировали учетную запись. Вам на почту
    br
    |отправлено  письмо со ссылкой для активации аккаунта.

  .redirect-block
    | Через &nbsp;
    span#timer
      | 10
    | &nbsp;секунд вы попадёте на &nbsp;
    = link_to 'vedomosti.ru', root_path

  javascript:
    var interval = window.setInterval(function() {
      var timeLeft = document.getElementById('timer').innerHTML;
      if(timeLeft * 1 == 0){
        window.clearInterval(interval)
        window.location = ("#{root_path}");
      }
      else
      {
        document.getElementById('timer').innerHTML = timeLeft * 1 - 1;
      }
    }, 1000);

app/views/session/blocked_user.mobile.slim
- render_title('Аккаунт заблокирован')

= render 'm/blocks/caption_and_menu'

.b-document.b-document_user-block
  h1 К сожалению, Ваш аккаунт заблокирован
  p
    |Вы были заблокированы, так как не активировали учетную запись. Вам на почту
    br
    |отправлено  письмо со ссылкой для активации аккаунта.

  .redirect-block
    | Через &nbsp;
    span#timer
      | 10
    | &nbsp;секунд вы попадёте на &nbsp;
    = link_to 'vedomosti.ru', root_path

  javascript:
    var interval = window.setInterval(function() {
      var timeLeft = document.getElementById('timer').innerHTML;
      if(timeLeft * 1 == 0){
        window.clearInterval(interval)
        window.location = ("#{root_path}");
      }
      else
      {
        document.getElementById('timer').innerHTML = timeLeft * 1 - 1;
      }
    }, 1000);

app/views/session/sign_in_form.html.slim
/формирование title для страницы
- render_title('Вход на сайт')

.b-sign-in-container
  .b-subscription-form-box

    .b-subscription-form-fieldset.b-subscription-form-fieldset_left
      = form_for @sign_in_form, url: '/sign_in_with_password', html: { class: 'b-form' } do |f|
        .b-subscription-form-field_social__header Вход на сайт

        .b-subscription-form-field.b-subscription-form-field_sign-in
          span.b-subscription-form-field__icon
            i.b-icon.icon-input-email
          = f.text_field :email, class: 'b-subscription-form__text b-subscription-form__text_login', placeholder: 'E-mail'
          - if @sign_in_form.errors[:email].present?
            .error= @sign_in_form.errors[:email].first

        .b-subscription-form-field.b-subscription-form-field_sign-in
          span.b-subscription-form-field__icon
            i.b-icon.icon-input-pass
          = f.password_field :password, class: 'b-subscription-form__text b-subscription-form__text_password', placeholder: 'Пароль'
          - if @sign_in_form.errors[:password].present?
            .error= @sign_in_form.errors[:password].first

        .b-subscription-form-field.b-subscription-form-field_sign-in
          = link_to 'Забыли пароль?', password_reset_email_form_path, class: 'restore_password'

        .b-subscription-form-field.b-subscription-form-field_sign-in
          button.b-subscription-button.b-subscription-button_long.b-subscription-button_small{type='submit'} Войти

      .b-subscription-form-field
        .sign-up
          i.b-icon.icon-key
          | Нет аккаунта на vedomosti.ru? #{link_to 'Зарегистрируйтесь', '/sign_up'}

    div.b-form-divider
    - if !defined?(hide_social_auth)
      .b-subscription-form-fieldset.b-subscription-form-fieldset_right
        = render 'register/oauth_links'

app/views/session/too_many_sessions.html.slim
.b-document.b-document_user-block
  h1 Слишком много открытых сессий.

  .redirect-block
    | Через &nbsp;
    span#timer
      | 10
    | &nbsp;секунд вы попадёте на &nbsp;
    = link_to 'vedomosti.ru', root_path

  javascript:
    var interval = window.setInterval(function() {
      var timeLeft = document.getElementById('timer').innerHTML;
      if(timeLeft * 1 == 0){
        window.clearInterval(interval)
        window.location = ("#{root_path}");
      }
      else
      {
        document.getElementById('timer').innerHTML = timeLeft * 1 - 1;
      }
    }, 1000);

app/views/session/too_many_sessions.mobile.slim
- render_title('Слишком много открытых сессий')

= render 'm/blocks/caption_and_menu'

.b-document.b-document_user-block
  h1 Слишком много открытых сессий.

  .redirect-block
    | Через &nbsp;
    span#timer
      | 10
    | &nbsp;секунд вы попадёте на &nbsp;
    = link_to 'vedomosti.ru', root_path

  javascript:
    var interval = window.setInterval(function() {
      var timeLeft = document.getElementById('timer').innerHTML;
      if(timeLeft * 1 == 0){
        window.clearInterval(interval)
        window.location = ("#{root_path}");
      }
      else
      {
        document.getElementById('timer').innerHTML = timeLeft * 1 - 1;
      }
    }, 1000);