config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get '/main' => 'main#index'

  get '/:region_slug' => 'main#index', region_slug: /spb|siberia|south|volga/

  get '/rubrics/:rubric_slug' => 'main#rubric', rubric_slug: /[a-z0-9_]+/, as: :rubric
  get '/rubrics/:rubric_slug/:subrubric_slug' => 'main#subrubric', rubric_slug: /[a-z0-9_]+/, subrubric_slug: /[a-z0-9_]+/, as: :subrubric

  # parts
  get '/parts/:part_slug' => 'main#part', part_slug: /[a-z0-9_]+/, as: :part
  get '/parts/:part_slug/:subpart_slug' => 'main#subpart', part_slug: /video/, subpart_slug: /[a-z0-9_]+/, as: :subpart

  # newspaper
  get '/newspaper/:year/:month/calendar'   => 'newspaper#calendar', year: /\d{4}/, month: /\d{2}/
  get '/newspaper/:year/:month/:day'       => 'newspaper#by_date',  year: /\d{4}/, month: /\d{2}/, day: /\d{2}/, as: :newspaper
  get '/newspaper/last'                    => 'newspaper#by_date', as: :newspaper_last

  # vedomosti&
  get '/partner'                         => 'partner#index'
  get '/partner/:year/:month/:day'       => 'partner#by_date',  year: /\d{4}/, month: /\d{2}/, day: /\d{2}/
  get '/partner/last'                    => 'partner#by_date'
  get '/partner/*url'                    => 'partner#show'

  # newspaper flash.xml
  get '/newspaper/:year/:month/:day/flash' => 'newspaper#flash', year: /\d{4}/, month: /\d{2}/, day: /\d{2}/, as: :newspaper_flash
  get '/newspaper/last/flash'              => 'newspaper#flash', as: :newspaper_last_flash
  get '/newspaper',                        to: redirect('/newspaper/last')

  # story
  get '/story/:slug' => 'stories#show', slug: /[a-z0-9_]+/, as: :stories
  get '/story/:slug/news' => 'stories#news', slug: /[a-z0-9_]+/

  # newsline
  get '/newsline'              => 'newsline#index', top: true
  get '/newsline(/top)'        => 'newsline#index', top: true
  get '/newsline/:rubric_slug' => 'newsline#index', rubric_slug: /[a-z0-9_]+/, as: :rubric_news

  get '/newsline/news/*oldurl' => 'document#oldnews' # для новостей со старыми урлами
  get '/fast_news'             => redirect('/newsline')

  # search
  get '/search' => 'search#index'

  # sign up
  get  '/sign_up' => 'register#sign_up_form'
  post '/sign_up_with_password' => 'register#sign_up_with_password'

  # password reset
  get  '/password_reset'                       => 'register#email_form',  as: :password_reset_email_form
  post '/password_reset'                       => 'register#check_email', as: :password_reset_email_send

  get  '/password_reset/:password_reset_token' => 'register#password_form',   password_reset_token: /[a-z0-9_]+/, as: :password_form
  post '/password_reset/:password_reset_token' => 'register#password_update', password_reset_token: /[a-z0-9_]+/, as: :password_send

  get  '/auth/:provider/callback' => 'register#oauth_callback', provider: /[a-z0-9_]+/
  post '/sign_up_with_oauth'      => 'register#sign_up_with_oauth'

  # sign in / out
  get  '/sign_in'  => 'session#sign_in_form', as: :sign_in
  get  '/sign_out' => 'session#sign_out',     as: :sign_out

  # sign in with password
  post '/sign_in_with_password' => 'session#sign_in_with_password'

  get '/blocked_user'      => 'session#blocked_user'
  get '/too_many_sessions' => 'session#too_many_sessions', as: :sessions_limit

  # sign in with oauth
  post '/sign_in_with_oauth'    => 'session#sign_in_with_oauth'
  get  '/auth/failure' => 'register#oauth_failure'

  get '/includes/session/yes'               => 'includes#get_session'
  get '/includes/popular24'                 => 'includes#popular24', as: :popular24
  get '/includes/story/:slug'               => 'includes#story', slug: /[a-z0-9_]+/
  get '/includes/redline'                   => 'includes#redline'
  get '/includes/companies/:slug/materials' => 'includes#materials_of_company'
  get '/includes/people/:slug/materials'    => 'includes#materials_of_person'

  # user registration confirm
  get  '/confirm' => 'register#confirm'

  # user profile include
  get '/includes/long_cache/user_profile(/:access_token)'          => 'includes#user_profile', owl_state: 'guest',               access_token: /[a-f0-9]+/
  get '/includes/long_cache/user_profile/:owl_state/:access_token' => 'includes#user_profile', owl_state: /guest|registered|authenticated/, access_token: /[a-f0-9]+/

  get '/includes/metynnis/*url' => 'includes#metynnis'

  get '/owl/body/:owl_status/:owl_reason/:owl_state/*url(.:format)' => 'document#owl_show', format: /json|html|xml/

  get '/includes/owl_smart/:owl_status/:owl_reason/:owl_state/newspaper/:year/:month/:day/issue' => 'newspaper#owl_newspaper_issue', year: /\d{4}/, month: /\d{2}/, day: /\d{2}/

  #online
  get 'online/template' => 'online#index'

  # libraries
  get '/library' => 'libraries#index', as: :libraries
  get '/library/:slug' => 'libraries#show', slug: /[a-z0-9_]+/, as: :library

  # sessions
  get '/session'               => 'session#create'
  get '/user/profile'          => 'users#show', as: :users_show
  post '/user/profile'         => 'users#update', as: :users_update
  post '/profile/accept_promo' => 'users#accept_promo'

  # info
  namespace :info, defaults: { controller: 'info' } do
    get  '/',         action: 'index'
    get  '/feedback', action: 'feedback'
    post '/feedback', action: 'send_feedback'
    get  '/contacts', action: 'contacts'
    get  '/:slug',    action: 'show', slug: /[a-z0-9_-]+/
  end

  # multimedia
  get '/multimedia' => 'main#multimedia'

  # podcasts
  get '/podcast'                    => redirect('/podcasts/last')
  get '/podcasts'                   => redirect('/podcasts/last')
  get '/podcasts/last'              => 'podcasts#last'
  get '/podcasts/:year/:month/:day' => 'podcasts#by_date'

  get '/tests/*url/q:step'             => 'tests#show'
  get '/tests/*url/r:result_id'        => 'tests#result'
  get '/tests/*url/s:index'            => 'tests#share'
  get '/tests/*url'                    => 'tests#show'
  get '/:rubric/test/*url/q:step'      => 'tests#show'
  get '/:rubric/test/*url/r:result_id' => 'tests#result'
  get '/:rubric/test/*url/s:index'     => 'tests#share'
  get '/:rubric/test/*url'             => 'tests#show'


  # broadcastings
  get '/:rubric/online/*url/check_new_posts/(:start_date)' => 'broadcastings#check_new_posts'
  get '/:rubric/online/*url/p:page' =>                        'broadcastings#show', page: /[1-9][0-9]*/
  get '/:rubric/online/*url' =>                               'broadcastings#show', page: 1

  # companies
  namespace :companies, defaults: { controller: 'companies' } do
    get '/'                                      => redirect('companies/index')
    get '/search',                               action: 'search'
    get '/:filter/',                             action: 'main', filter: /index|industries/
    get '/:filter/:slug',                        action: 'by_filter', filter: /index|industries/
    get '/:filter/:slug/groups/:group',          action: 'by_group', filter: /index|industries/
    get '/:slug',                                action: 'show', slug: /[a-z0-9_\-]+/, tab: 'about'
    get '/:slug/press_releases',                 action: 'press_releases', slug: /[a-z0-9_\-]+/
    get '/:slug/press_releases/:year',           action: 'press_releases_by_year', slug: /[a-z0-9_\-]+/, year: /\d{4}/

    get '/:slug/company_messages',               action: 'company_messages', slug: /[a-z0-9_\-]+/
    get '/:slug/company_messages/:year(/:page)', action: 'company_messages', slug: /[a-z0-9_\-]+/, year: /\d{4}/, page: /\d+/

    get '/:slug/all_press_releases',             action: 'all_press_releases', slug: /[a-z0-9_\-]+/
    get '/:slug/:tab',                           action: 'show', slug: /[a-z0-9_\-]+/, tab: /about|kso|policy/
  end
  get '/press_releases/*suburl'                  => 'companies#press_release'
  get '/company_messages/*suburl'                => 'companies#company_message'

  # people
  namespace :people, defaults: { controller: 'people' } do
    get '/'                               => redirect('people/index')
    get '/:filter',                       action: 'main', filter: /index/
    get '/:filter/:slug',                 action: 'by_filter', constraints: ->(req) { CGI::unescape(req.params[:slug]) =~ /[А-ЯЁA-Z]/ }, filter: /index/
    get '/:filter/:slug/groups/:group',   action: 'by_group',  constraints: ->(req) { CGI::unescape(req.params[:slug]) =~ /[А-ЯЁA-Z]/ && CGI::unescape(req.params[:group]) =~ /[А-ЯЁA-Z][а-яёa-z]+\s—\s[А-ЯЁA-Z][а-яёa-z]+/ }, filter: /index/
    get '/:filter/search',                action: 'search', filter: /index/
    get '/*url',                          action: 'show'
  end
  
  # mobile version
  constraints(SubdomainConstraints::M) do
    scope module: :m do
      get '/user/profile'  => 'users#show',   as: :m_users_show
      post '/user/profile' => 'users#update', as: :m_users_update
      get '/newsline/top/*url' => 'document#show', top: true
      get '/newsline/*url'     => 'document#show'
      get '/*url'              => 'document#show'
    end
  end

  namespace :advert, defaults: { controller: 'advert' } do
    get '/main', action: 'main'
    get '/noteads', action: 'noteads'
    get '/teads', action: 'teads'
    get '/mobile_main', action: 'mobile_main'
  end

  # subscription
  namespace :subscription, defaults: { controller: 'subscription' } do
    get '/',      action: 'engineering_works'
    get '/step1', action: 'engineering_works'
    get '/step2', action: 'engineering_works'
    get '/step3', action: 'engineering_works'

    get '/corporate',        action: 'corporate'
    get '/gift',             action: 'gift'
    get '/representational', action: 'representational'

    get '/prices', action: 'prices'

    post '/payment/card',    action: 'payment_card'
    post '/payment/yandex',  action: 'payment_yandex'

    get '/card_order_check/:uuid', action: 'card_order_check', uuid: /[a-f0-9\-]+/

    post '/card_callback',        action: 'card_callback'

app/controllers/api/v1/register_controller.rb
module Api
  module V1
    class RegisterController < ApplicationController
      skip_before_filter :verify_authenticity_token
      
      def sign_up_with_password
        registration_form = PasswordRegistrationForm.new(
          access_token: access_token,
          ip: request.ip,
          **params.fetch(:user_with_password, {}).symbolize_keys
        )
        
        use_case = SignUpWithPassword.new(registration_form)
        use_case.call
        
        if use_case.success?
          render json: use_case.user_data
        else
          render json: registration_form.errors, status: :unprocessable_entity
        end
      end
      
      def sign_up_with_oauth
        use_case = SignUpWithOauthToken.new(params[:user_with_oauth], request.ip, access_token)
        
        if use_case.call
          render json: use_case.user
        else
          render json: use_case.errors, status: :unprocessable_entity
        end
      end
      
      def check_email
        use_case = SendPasswordResetEmail.new(params[:email], request.ip)
        use_case.call
        
        if use_case.success?
          render json: { status: 'ok' }
        else
          render json: { status: 'error', errors: ['Пользователь с таким e-mail не найден.'] }, status: :unprocessable_entity
        end
      end
    end
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  layout 'auth'

  def sign_up_form
    @registration_form = PasswordRegistrationForm.new
  end

  def sign_up_with_password
    @registration_form = PasswordRegistrationForm.new(
      access_token: access_token,
      ip: request.ip,
      **params.fetch(:password_registration_form, {}).symbolize_keys
    )

    use_case = SignUpWithPassword.new(@registration_form)
    use_case.call

    if use_case.new_token.present?
      response.headers['Set-Cookie'] = token_cookie_header(use_case.new_token)
    end

    if use_case.success?
      respond_to do |format|
        format.html   { delete_cookie_and_redirect }
        format.mobile { delete_cookie_and_redirect }
        format.json   { render json: use_case.user_data }
      end
    else
      respond_to do |format|
        format.html   { render 'register/sign_up_form' }
        format.mobile { render 'm/register/sign_up_form' }
        format.json   { render json: @registration_form.errors, status: :unprocessable_entity }
      end
    end
  end

  def oauth_callback
    @form = OauthRegistrationForm.from_auth_hash(
      auth_hash,
      ip: request.ip,
      access_token: access_token
    )

    use_case = SignInWithOauth.new(@form)
    use_case.call

    if use_case.new_token.present?
      response.headers['Set-Cookie'] = token_cookie_header(use_case.new_token)
    end

    if use_case.success?
      delete_cookie_and_redirect
    elsif use_case.blocked?
      redirect_to blocked_user_url
    elsif use_case.too_many_sessions?
      redirect_to sessions_limit_url
    else
      respond_to do |format|
        format.html
        format.mobile
      end
    end
  end

  def sign_up_with_oauth
    @form = OauthRegistrationForm.new(
      access_token: access_token,
      ip: request.ip,
      **params[:oauth_registration_form].symbolize_keys
    )

    use_case = SignUpWithOauth.new(@form)
    use_case.call

    if use_case.success?
      delete_cookie_and_redirect
    else
      respond_to do |format|
        format.html { render 'register/oauth_callback' }
        format.mobile { render 'm/register/oauth_callback' }
      end
    end
  end

  def oauth_failure
    render text: 'failure'
  end

  def confirm
    if User.confirm(params[:token], request.ip)
      delete_cookie_and_redirect #, notice: 'ok'
    else
      redirect_to users_show_url, notice: 'fail'
    end
  end

  def email_form
    @email_form = EmailForm.new
  end

  def check_email
    @email_form = EmailForm.new(params[:email_form])

    if @email_form.valid?
      use_case = SendPasswordResetEmail.new(params[:email_form][:email], request.ip)
      use_case.call
      @success = use_case.success?
      @email_form.errors.add(:email, :not_found) unless @success
    end

    respond_to do |format|
      format.html { render 'register/email_form' }
      format.mobile { render 'm/register/email_form' }
    end
  end

  def password_form
    use_case = CheckPasswordResetToken.new(params[:password_reset_token], request.ip)
    use_case.call

    @password_form = PasswordForm.new
    @check_token_success = use_case.success?
  end

  def password_update
    @check_token_success = true

    @password_form = PasswordForm.new(params[:password_form])

    if @password_form.valid?
      use_case = ResetPassword.new(
        params[:password_form][:password],
        params[:password_reset_token],
        access_token,
        request.ip
      )
      use_case.call

      @success = use_case.success?
      @password_form.errors.add(:password, :unknown_error) unless @success
    end

    respond_to do |format|
      format.html { render 'register/password_form' }
      format.mobile { render 'm/register/password_form' }
    end
  end

private
  def auth_hash
    request.env['omniauth.auth']
  end
end

app/views/register/_header.html.slim
.title
  |Регистрация
.subtitle
  |Добро пожаловать в Сообщество читателей «Ведомостей».

.descr
p
  |После регистрации Вы сможете читать до 13 материалов vedomosti.ru в месяц. Если хотите читать больше, оформите подписку.
  br
  | Мы рекомендуем регистрироваться под настоящим именем и оставляем за собой право удалять некорректную информацию.
  br
  | АО «Бизнес Ньюс Медиа» обязуется использовать персональные данные своих пользователей в соответствии с Правилами регистрации и конфиденциальности.

app/views/register/_oauth_form.html.slim
.b-form
  = form_for(@form, url: sign_up_with_oauth_path, html: { name: 'oauth_form' }) do |f|
    = f.label :email, 'E-mail *'
    = f.text_field :email, placeholder: 'mail@example.com'
    - if @form.errors[:email].present?
      .error= @form.errors[:email].first

    = f.label :nickname, 'Ник'
    = f.text_field :nickname, placeholder: 'Бэтмэн'
    - if @form.errors[:nickname].present?
      .error= @form.errors[:nickname].first

    = f.label :last_name, 'Фамилия *'
    = f.text_field :last_name, placeholder: 'Петров'
    - if @form.errors[:last_name].present?
      .error= @form.errors[:last_name].first

    = f.label :first_name, 'Имя *'
    = f.text_field :first_name, placeholder: 'Вася'
    - if @form.errors[:first_name].present?
      .error= @form.errors[:first_name].first

    = f.label :phone, 'Телефон *'
    = f.text_field :phone, placeholder: '+7 999 123-45-67'
    - if @form.errors[:phone].present?
      .error= @form.errors[:phone].first

    br
    | В формате 7–495–2321750, то есть код страны–код города–телефон

    br

    .b-rules__wrapper
      = f.check_box :rules
      = f.label :rules, 'Я согласен с Правилами регистрации и конфиденциальности.'

    br
      = f.submit 'отправить', class: 'b-button b-button_submit'

app/views/register/_oauth_links.html.slim
.b-subscription-form-field_social__header Быстрый вход через соц.сети
.b-subscription-form-field.b-subscription-form-field_social
  button.b-subscription-button.b-subscription-button_small.b-subscription-button_facebook type='button' onClick='window.location.href="/auth/facebook"' Facebook
  button.b-subscription-button.b-subscription-button_small.b-subscription-button_twitter type='button' onClick='window.location.href="/auth/twitter"' Twitter
  button.b-subscription-button.b-subscription-button_small.b-subscription-button_vkontakte type='button' onClick='window.location.href="/auth/vkontakte"' Вконтакте

app/views/register/_password_form.html.slim
= form_for(@registration_form, url: { controller: 'register', action: 'sign_up_with_password' }, html: { class: 'b-form' }) do |f|
  .b-subscription-form-field
    = f.text_field :email, class: 'b-subscription-form__text', 'placeholder' => 'E-mail *'
    - if @registration_form.errors[:email].present?
      .error= @registration_form.errors[:email].first

  .b-subscription-form-field
    = f.password_field :password, class: 'b-subscription-form__text', 'placeholder' => 'Пароль (6-20 символов) *'
    - if @registration_form.errors[:password].present?
      .error= @registration_form.errors[:password].first

  .b-subscription-form-field
    = f.password_field :password_confirmation, class: 'b-subscription-form__text', 'placeholder' => 'Повторите пароль *'
    - if @registration_form.errors[:password_confirmation].present?
      .error= @registration_form.errors[:password_confirmation].first

  .b-subscription-form-field
    = f.text_field :last_name, class: 'b-subscription-form__text', 'placeholder' => 'Фамилия *'
    - if @registration_form.errors[:last_name].present?
      .error= @registration_form.errors[:last_name].first

  .b-subscription-form-field
    = f.text_field :first_name, class: 'b-subscription-form__text', 'placeholder' => 'Имя *'
    - if @registration_form.errors[:first_name].present?
      .error= @registration_form.errors[:first_name].first

  - if !defined?(hide_nickname) || (defined?(hide_nickname) && !hide_nickname)
    .b-subscription-form-field
      = f.text_field :nickname, class: 'b-subscription-form__text', 'placeholder' => 'Ник'
      - if @registration_form.errors[:nickname].present?
        .error= @registration_form.errors[:nickname].first

  .b-subscription-form-field
    = f.text_field :phone, class: 'b-subscription-form__text', 'placeholder' => 'Телефон *'
    div.phone-descr
      | В формате 7–495–2321750
    = f.hidden_field :rules, value: '1'
    - if @registration_form.errors[:phone].present?
      .error= @registration_form.errors[:phone].first

  .b-subscription-form-field.checkboxes
    input.checkboxes-input{type="checkbox" name="registrationCheckbox" id="registrationCheckbox" ng-model="agreement"}
    label.checkboxes-label{for="registrationCheckbox"}
      | Я согласен с правилами #{link_to 'регистрации и конфиденциальности', '/info/privacy', class: 'green-link'}

  br
    button.b-subscription-button.b-subscription-button_long.b-subscription-button_small{type='submit' ng-click = 'submit()' ng-disabled="!agreement"} Зарегистрироваться

app/views/register/email_form.html.slim
.b-document.b-document_password-reset
  .b-form__wrapper
    .b-form.b-form_reset-password
      - if @success
        div.b-form__success
          .b-form__success__header
            | Проверьте вашу почту
          .b-form__success__text
            | Вам отправлено письмо со ссылкой для восстановления пароля.
            div = link_to 'Перейти на главную страницу', root_path
      - else
        .b-form__header Сброс забытого пароля
        = form_for @email_form, url: password_reset_email_send_path do |f|
          = f.label :email, 'Укажите Вашу почту и мы отправим Вам ссылку для сброса пароля', class: 'b-form__field__label'
          .b-form__field
            = f.text_field :email, class: 'b-form__field__text', placeholder: 'E-mail'
            - if @email_form.errors[:email].present?
              .b-form__error = @email_form.errors[:email].join(?,)
          .b-form__field
            button.b-form__button{type='submit'} Сбросить

app/views/register/oauth_callback.html.slim
.b-document
  .b-form-page
    = render 'header'
    = render 'oauth_form'

app/views/register/password_form.html.slim
.b-document.b-document_password-reset2
  .b-form__wrapper
    .b-form.b-form_reset-password2
      - if @check_token_success
        - if @success
          .b-form__success
            .b-form__success__header Пароль успешно обновлён.
            .b-form__success__text = link_to 'Перейти на главную страницу', root_path

        - else
          .b-form__header Ввод нового пароля
          = form_for @password_form, url: password_send_path do |f|
            = f.label :password, 'Введите новый пароль', class: 'b-form__field__label'
            .b-form__field
              = f.password_field :password, class: 'b-form__field__text'
              - if @password_form.errors[:password].present?
                .b-form__error = @password_form.errors[:password].join(', ')

            = f.label :password_confirmation, 'Подтвердите новый пароль', class: 'b-form__field__label'
            .b-form__field
              = f.password_field :password_confirmation, class: 'b-form__field__text'
              - if @password_form.errors[:password_confirmation].present?
                .b-form__error = @password_form.errors[:password_confirmation].first

              button.b-form__button{type='submit'} Отправить
              /div = f.submit 'Отправить', class: 'b-button b-button_submit'

      - else
        .b-form__header
          | Ввод нового пароля <br> Неправильный токен сброса пароля.

app/views/register/sign_up_form.html.slim
.b-sign-in-container
  .b-subscription-form-fieldset.b-subscription-form-fieldset_left
    .b-subscription-form-field_social__header
      | Регистрация
    = render 'register/password_form', hide_nickname: defined?(hide_nickname) ? hide_nickname : false
  - if !defined?(hide_social_auth)
    .b-subscription-form-fieldset.b-subscription-form-fieldset_right
      = render 'register/oauth_links'